title: Kieran's Components
description: Explore the world of UI
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-midnight
sass:
    sass_dir: _sass
collections: 
  - projects
plugins:
  - jekyll-sitemap
